# Generated by Django 4.2.11 on 2024-03-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_cart_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="user_id",
            field=models.IntegerField(),
        ),
    ]
