# Generated by Django 4.2.11 on 2024-03-08 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_cart_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="price",
        ),
    ]
