# Generated by Django 4.2.11 on 2024-03-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_remove_cart_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="cart",
            name="quantity",
            field=models.IntegerField(),
        ),
    ]
