# Generated by Django 4.2.11 on 2024-03-08 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_cart_quantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="price",
            new_name="unit_price",
        ),
    ]
